name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup project
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn run build --if-present

      - name: Unit Tests
        run: yarn test --coverage

      - name: Upload to codecov
        uses: codecov/codecov-action@v1

      - name: Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          start: yarn start
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
